version: '3.7'

services:
  postgres-townsq:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'TOWNSQ'
      POSTGRES_USER: 'devdbuser'
      POSTGRES_PASSWORD: 'devdbpass'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init-files:/docker-entrypoint-initdb.d
    networks:
      - postgres-pgadmin-network

  pgadmin-townsq:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpass
    ports:
      - "8000:80"
    networks:
      - postgres-pgadmin-network

networks:
  postgres-pgadmin-network:

volumes:
  postgres-data:
