spring:
  application:
    name: TownSq
  # Jpa Properties
  datasource:
    url: jdbc:postgresql://localhost:5432/TOWNSQ?currentSchema=townsq
    username: devdbuser
    password: devdbpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  h2:
    console:
      enabled: false
  liquibase:
    enabled: false
    change-log: database/db.changelog-dev.xml
  resources:
    static-locations: classpath:/static/,file:src/main/resources/static/

misc:
  root-url: http://localhost:8080/